### ISSUE TITLE
Peer to Peer review

### ISSUE THREAD

**Issue by Al-Amin-Khan-Shakil** [Dorcas126/Setup-and-mobile-first-project#5]
**Shakil:** I think you should put you name on readme file in author section instead of Author1. 

**Elo:** I think instead of 2 package.json file you can have one and ignore the other one.

**Lucy:** I think you should remove "_NOTE: we recommend using the [MIT license]"  this line from your readme file.

**Comment by Dorcas126** [comment]
Issue suggested by my partners are resolved
